let squares = [
    "someone else has a crush on the love interest",
    "a crisis at work",
    "eggnog",
    "an actor from a tv series",
    "kids that need help with something",
    "a big city boyfriend",
    "a concerned parent or grandparent",
    "a tree lighting",
    "shopping for a Christmas tree",
    "a family heirloom",
    "talking about someone who is dead",
    "mistletoe",
    "sentimental gift",
    "welcomed home by an old acquaintance",
    "a visit to a coffee shop, bakery, or restaurant",
    "someone reveals their dream job",
    "a christmas party",
    "love interest is a widow",
    "strolling through town",
    "children in Christmas costumes",
    "baked goods",
    "telling a story about childhood",
    "love interests kiss",
    "driving down snowy roads",
    "an old flame reappears",
    "making a family recipe",
    "hot cocoa",
    "a small town business is in trouble",
    "decorating a christmas tree",
    "main character lost a parent",
    "a former child star is starring",
    "aloof boyfriend",
    "it's snowing",
    "a cute pet dog",
    "santa",
    "small town christmas shopping",
    "carol singing",
    "flashback to childhood",
    "twinkle lights",
    "main character can't stay in town for long",
    "small town christmas events",
    "main character stressing about work",
    "unexpectedly running into the love interest",
    "a character that doesn't like christmas",
    "airport scene",
    "someone encourages a relationship",
    "drinking coffee",
    "an awkward situation",
    "an almost kiss",
    "someone has a secret identity",
    "aerial shot of a small town or city",
    "Christmas sweaters",
    "'things are different in a small town'",
    "a journalist, baker, wedding planner, or photographer",
    "new york is mentioned",
    "ice skating, sledding, or skiing",
    "the sheriff or a doctor makes an appearance",
    "love interests seeing each other all dressed up",
    "someone living in a home they probably can't afford",
    "someone misunderstands a situation",
    "name another movie one of the leads has been in",
    "amnesia",
    "talking about the meaning of Christmas",
    "something clumsy happens",
    "people coming together to save the day",
    "sharing holiday memories",
    "doing something nice for others",
    "the town has a silly name",
    "someone doesn't have enough money",
    "a Christmas pun",
    "someone gives an awkward speech",
    "a random crafty skill",
    "wisdom from a parent",
    "excessive christmas decor",
    "a fake accent",
    "predict the next line",
    "actor pretends to have a skill",
    "cutting down a tree",
    "a snowball fight",
    "a character is a widow",
    "a single parent",
    "royalty",
    "a gay best friend",
    "spying on someone",
    "weather interferes with plans",
    "the 'let me show you how' touch",
    "nutcracker",
    "peppermint/candy cane",
    "an obvious villain",
    "love interests don't get along at first",
    "the love interest reads to children",
    "a nepo baby",
    // "a knowing look",
]

export default squares